create table if not exists public.reservations (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    date date not null,
    time time without time zone not null,
    party_size integer not null check (party_size > 0),
    phone text,
    notes text,
    created_at timestamptz not null default now(),
    status text not null default 'confirmed'
);

create index if not exists idx_reservations_date_time
    on public.reservations (date, time);
